const q1 = document.getElementById("a");
const q2 = document.getElementById("b");
const q3 = document.getElementById("c");
const q4 = document.getElementById("d");
const highScoreBtn = document.getElementById('h_score');
const startBtn = document.getElementById('start-btn');
const nameInput = document.getElementById('user-name');
const tracker = document.getElementById('tracker');
const scoreDisplay = document.getElementById('score');

let currentQuestion = null;
let score = 0;
let questionCount = 0;


const question_array = [
    {
        question: "What is the capital of France?",
        a: "Berlin",
        b: "Paris", c: "Madrid", d: "Rome", correct: "b"
    },
    { question: "What is 2 + 2?", 
        a: "3", 
        b: "4", 
        c: "5", 
        d: "6", 
        correct: "b" },
    { question: "Largest planet in solar system?", 
        a: "Jupiter", 
        b: "Saturn", 
        c: "Neptune", 
        d: "Uranus", 
        correct: "a" },
    { question: "Who wrote 'Hamlet'?", 
        a: "Dickens", 
        b: "Shakespeare", 
        c: "Austen", 
        d: "Twain", 
        correct: "b" },
    { question: "Symbol for gold?", 
        a: "Ag", 
        b: "Au", 
        c: "Fe", 
        d: "Pb", 
        correct: "b" },
    { question: "Smallest prime number?", 
        a: "0", 
        b: "1", 
        c: "2", 
        d: "3", 
        correct: "c" },
    { question: "Year Titanic sank?", 
        a: "1912", 
        b: "1913", 
        c: "1914", 
        d: "1915", 
        correct: "a" },
    { question: "Hardest natural substance?", 
        a: "Gold", 
        b: "Diamond", 
        c: "Iron", 
        d: "Platinum", 
        correct: "b" },
    { question: "Who painted Mona Lisa?", 
        a: "Van Gogh", 
        b: "Picasso", 
        c: "Da Vinci", 
        d: "Dalí", 
        correct: "c" },
    { question: "Largest mammal?", 
        a: "Blue Whale", 
        b: "Elephant", 
        c: "Giraffe", 
        d: "Hippo", 
        correct: "a" },
    { question: "Boiling point of water?", 
        a: "90°C", 
        b: "100°C", 
        c: "110°C", 
        d: "120°C", 
        correct: "b" },
    { question: "The Red Planet?", 
        a: "Earth", 
        b: "Mars", 
        c: "Venus", 
        d: "Jupiter", 
        correct: "b" },
    { question: "Guacamole ingredient?", 
        a: "Tomato", 
        b: "Onion", 
        c: "Lime", 
        d: "Avocado", 
        correct: "d" },
    { question: "Father of Computers?", 
        a: "Turing", 
        b: "Babbage", 
        c: "Gates", 
        d: "Jobs", 
        correct: "b" },
    { question: "Currency of Japan?", 
        a: "Yen", 
        b: "Won", 
        c: "Yuan", 
        d: "Euro", 
        correct: "a" },
    { question: "Gas plants absorb?", 
        a: "Oxygen", 
        b: "CO2", 
        c: "Nitrogen", 
        d: "Hydrogen", 
        correct: "b" },
    { question: "Discovered penicillin?", 
        a: "Curie", 
        b: "Fleming", 
        c: "Pasteur", 
        d: "Lister", 
        correct: "b" },
    { question: "Largest ocean?", 
        a: "Atlantic", 
        b: "Indian", 
        c: "Pacific", 
        d: "Arctic", 
        correct: "c" },
    { question: "Smallest country?", 
        a: "Monaco", 
        b: "Vatican City", 
        c: "San Marino", 
        d: "Liechtenstein", 
        correct: "b" },
    { question: "Formula for water?", 
        a: "H2O", 
        b: "CO2", 
        c: "NaCl", 
        d: "O2", 
        correct: "a" },
    { question: "How many continents?", 
        a: "5", 
        b: "6", 
        c: "7", 
        d: "8", 
        correct: "c" },
    { question: "Fastest land animal?", 
        a: "Lion", 
        b: "Cheetah", 
        c: "Leopard", 
        d: "Tiger", 
        correct: "b" },
    { question: "Earth's satellite?", 
        a: "Sun", 
        b: "Mars", 
        c: "Moon", 
        d: "Venus", 
        correct: "c" },
    { question: "Invented the lightbulb?", 
        a: "Tesla", 
        b: "Edison", 
        c: "Bell", 
        d: "Newton", 
        correct: "b" },
    { question: "Longest river?", 
        a: "Amazon", 
        b: "Nile", 
        c: "Mississippi", 
        d: "Yangtze", 
        correct: "b" },
    { question: "Highest mountain?", 
        a: "K2", 
        b: "Everest", 
        c: "Fuji", 
        d: "Denali", 
        correct: "b" },
    { question: "Square root of 81?", 
        a: "7", 
        b: "8", 
        c: "9", 
        d: "10", 
        correct: "c" },
    { question: "Primary colors?", 
        a: "R,G,B", 
        b: "R,Y,B", 
        c: "B,Y,G", 
        d: "R,Y,G", 
        correct: "b" },
    { question: "National animal of Scotland?", 
        a: "Lion", 
        b: "Eagle", 
        c: "Unicorn", 
        d: "Dragon", 
        correct: "c" },
    { question: "Current year?", 
        a: "2024", 
        b: "2025", 
        c: "2026", 
        d: "2027", 
        correct: "b" },
    { question: "Colors in a rainbow?", 
        a: "5", 
        b: "6", 
        c: "7", 
        d: "8", 
        correct: "c" },
    { question: "Which organ filters blood?", 
        a: "Heart", 
        b: "Liver", 
        c: "Kidney", 
        d: "Lungs", 
        correct: "c" },
    { question: "World's most populous city?", 
        a: "NYC", 
        b: "Shanghai", 
        c: "Tokyo", 
        d: "Delhi", 
        correct: "c" },
    { question: "Bones in human ear?", 
        a: 1, 
        b: 2, 
        c: 3, 
        d: 4, 
        correct:"c" },
    { question: "Symbol for Iron?", 
        a: "Ir", 
        b: "Fe", 
        c: "In", 
        d: "Au", 
        correct: "b" },
    { question: "Who wrote 'The Odyssey'?", 
        a: "Homer", 
        b: "Virgil", 
        c: "Socrates", 
        d: "Plato", 
        correct: "a" },
    { question: "Hottest planet?", 
        a: "Mercury", 
        b: "Venus", 
        c: "Mars", 
        d: "Jupiter", 
        correct: "b" },
    { question: "Smallest unit of matter?", 
        a: "Cell", 
        b: "Atom", 
        c: "Molecule", 
        d: "Proton", 
        correct: "b" },
    { question: "Powerhouse of the cell?", 
        a: "Nucleus", 
        b: "Ribosome", 
        c: "Mitochondria", 
        d: "Golgi", 
        correct: "c" },
    { question: "Who discovered gravity?", 
        a: "Einstein", 
        b: "Newton", 
        c: "Galileo", 
        d: "Hawking", 
        correct: "b" },
    { question: "Largest internal organ?", 
        a: "Heart", 
        b: "Lungs", 
        c: "Liver", 
        d: "Kidney", 
        correct: "c" },
    { question: "Elements in periodic table?", 
        a: "100", 
        b: "112", 
        c: "118", 
        d: "120", 
        correct: "c" },
    { question: "Language of Brazil?", 
        a: "Spanish", 
        b: "Portuguese", 
        c: "English", 
        d: "French", 
        correct: "b" },
    { question: "First man on the moon?", 
        a: "Aldrin", 
        b: "Armstrong", 
        c: "Collins", 
        d: "Gagarin", 
        correct: "b" },
    { question: "What is the 'Windy City'?", 
        a: "NYC", 
        b: "Chicago", 
        c: "Seattle", 
        d: "Miami", 
        correct: "b" },
    { question: "Octopus hearts?", 
        a: "1", 
        b: "2", 
        c: "3", 
        d: "4", 
        correct: "c" },
    { question: "What does CPU stand for?", 
        a: "Process Unit", 
        b: "Processing Unit", 
        c: "Core Unit", 
        d: "Computer Unit", 
        correct: "b" },
    { question: "Largest desert?", 
        a: "Sahara", 
        b: "Gobi", 
        c: "Antarctica", 
        d: "Arabian", 
        correct: "c" },
    { question: "First video game?", 
        a: "Pong", 
        b: "Tetris", 
        c: "Pac-Man", 
        d: "Tennis for Two", 
        correct: "d" },
    { question: "Statue of Liberty gift from?", 
        a: "UK", 
        b: "Germany", 
        c: "France", 
        d: "Italy", 
        correct: "c" }
];

function getRandomQuestion() {
    return quizPool[Math.floor(Math.random() * quizPool.length)];
}
  let quizPool = [...question_array].sort(() => Math.random() - 0.5).slice(0, 10);
function displayQuestion() {
    currentQuestion = getRandomQuestion();
    document.getElementById("question").innerText = currentQuestion.question;
    q1.innerText = currentQuestion.a;
    q2.innerText = currentQuestion.b;
    q3.innerText = currentQuestion.c;
    q4.innerText = currentQuestion.d;

    questionCount++;
    tracker.innerText = `Question: ${questionCount}`;
}

function startQuiz() {
    const name = nameInput.value.trim();
    if (name === "") {
        alert("Please enter your name first!");
        return;
    }
    
    if (!startBtn.classList.contains('started')) {
        startBtn.classList.add('started');
        startBtn.innerText = "Quiz Started";
        document.getElementById('quiz-container').style.display = 'block'; 
        displayQuestion();
        
    }
}


[q1, q2, q3, q4].forEach(btn => {
    btn.addEventListener('click', function () {
        if (this.id === currentQuestion.correct) {
            score += 10;
            scoreDisplay.innerText = `Score: ${score}`;
        }
        displayQuestion();
    });
});

startBtn.addEventListener('click', startQuiz);
highScoreBtn.addEventListener('click', () => alert("High scores coming soon!"));
